Improvements to instrument names translations
musescore/MuseScore pull request #11137
Opened 2022-04-10 23:21 UTC by cbjeukendrup

- Added disambiguations when translating instrument names, per instrument id and longName/shortName/trackName
- Merged generateTs.py into update_instruments_xml.py

2022-04-11 10:54 UTC, shoogle requested changes

2022-04-11 10:54 UTC, shoogle commented on share/instruments/instrumentsxml.h
> +QT_TRANSLATE_NOOP("InstrumentsXML", "*(C)"),
It was clever to use a translation comment like this but I think we will need disambiguation text even for the trait names. The reason is that we add special characters to the trait names to give them special meanings:

`*` - This is the most common trait name so use it as the default in the New Score Wizard dropdown.
`()` - This trait name should not appear in the score.

These are added to the translatable string to allow translators to choose a different default to use in their locale, and to hide or unhide the trait name in scores written in their language.

If the `//:` comment strings are actually exposed to translators then you could make use of it like this:

```c++
//: traitName codes: * most common for instrument; () hide in score
QT_TRANSLATE_NOOP3("InstrumentsXML", "*(C)", "piccolo|traitName"),
```

A translator could choose to translate `"*(C)"` for the piccolo as `"C"`, `"*C"`, `"(C)"` or `"*(C)"`, and they might make a different choice for a different instrument that also has `"*(C)"` as the trait name in English, hence we need disambiguation text.

2022-04-11 11:56 UTC, cbjeukendrup commented on share/instruments/instrumentsxml.h
> +QT_TRANSLATE_NOOP3("
Oops, that was by accident, by my git pre-commit hook. It just uncrustified every staged file. Fixed!

2022-04-11 12:04 UTC, cbjeukendrup commented on src/engraving/libmscore/instrtemplate.cpp
> +}
I'm not sure what to do about channels. It seems that before, they were not translated at all. I also believe that the whole idea of channels is being dropped anyway.

2022-04-11 12:12 UTC, shoogle commented on src/engraving/libmscore/instrtemplate.cpp
> +}
Let's keep them in the translation file for now so we don't have to add them again later after string freeze. There is only a relatively small number of them anyway.

BTW, my understanding is that channels have been dropped for MuseScore 4.0 to save time, but they may return in 4.1 in some form, though they may work very differently to before.

2022-04-11 12:22 UTC, shoogle requested changes

2022-04-11 12:22 UTC, shoogle commented on share/instruments/update_instruments_xml.py
> +                                                    'traitName codes: * most common for instrument; () hide in score')
Could you write 'longName', 'shortName' and 'trackName' even if the trait name is '[hide]'? We may need translations of those strings to identify instruments in older scores that don't have instrument IDs. I think we only started saving instrument IDs in MuseScore 3.5 or thereabouts, so in older scores we look at the instrument name. We're not doing this yet but there was a plan to do so, so we'll need them in before the string freeze.

Obviously we don't to translate the trait name if it is '[hide]', so you can keep that in the conditional statement.

2022-04-11 18:09 UTC, shoogle approved these changes
Awesome!

2022-04-18 13:01 UTC, RomanPudashkin approved these changes

2022-04-18 13:01 UTC, merged