Fix #314573: Indicate when note is outside the instrument range for screen readers
musescore/MuseScore pull request #13197
Opened 2022-09-06 13:15 UTC by HemantAntony

Resolves: [#314573](https://musescore.org/en/node/314573)

*(short description of the changes and the motivation to make the changes)*

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

2022-09-06 14:00 UTC, shoogle requested changes

2022-09-06 14:00 UTC, shoogle commented on src/engraving/libmscore/note.cpp
> +        }
Strings should be written like:
```c++
pitchOutOfRangeWarning = u" " + mtrc("engraving", "too low");
```
This provides a leading space (protected from translation) for use with the format string below, and avoids adding a leading space before `%4` in that format string itself (which would give an unnecessary space when `pitchOutOfRangeWarning` is empty).

2022-09-10 20:17 UTC, shoogle approved these changes

2022-09-11 07:57 UTC, RomanPudashkin approved these changes

2022-09-11 07:57 UTC, merged