gp-import: fixed import of ties for harmonic notes in gp5
musescore/MuseScore pull request #17639
Opened 2023-05-18 21:06 UTC by alexpavlov96

2023-05-19 07:49 UTC, mikekirin approved these changes

2023-05-19 08:41 UTC, abariska requested changes
@alexpavlov96 The build crashes when opening test tab (Cemetery gates)

2023-05-19 09:29 UTC, abariska approved these changes

2023-05-19 09:30 UTC, merged

2023-05-21 09:14 UTC, alexpavlov96 commented
@abariska crash described and fixed in https://github.com/musescore/MuseScore/pull/17664