Add MEI export for multiRest
musescore/MuseScore pull request #19520
Opened 2023-09-25 16:10 UTC by rettinghaus

@lpugin please have a look

2023-09-25 17:59 UTC, lpugin commented
This is what you need to add / change:

First of all the features implemented have import and export with a round trip test, so it should be the same here. You need to implement the importer, add a test case and make sure the round-trip test passes.

Most MEI elements are set in the MeiConverter class. That way we can have import / export in the same place as much as possible. You should do the same here.

2023-09-25 18:09 UTC, lpugin commented
It should be converted into a draft.

2023-09-26 06:14 UTC, lpugin commented on src/importexport/mei/internal/meiexporter.cpp
> +    if (mmR1->mmRestFirst()) {
You cannot call `mmRestFirst` without checking the validity of `mmR1`

2023-09-26 06:22 UTC, lpugin requested changes

2023-09-26 06:22 UTC, lpugin commented on src/importexport/mei/internal/meiexporter.cpp
> +
Make an `else` statement here and do not return in the `if` statement above. That way we do not start changing the value of `m_currentNode` at different places, which is quickly error prone.

2023-09-26 06:22 UTC, lpugin commented on src/importexport/mei/internal/meiexporter.cpp
> +        meiMultiRest.Write(multiRestNode, xmlId);
To be more inline with the rest of the exporter structure, make a `writeMultiRest` method for this.

2023-09-26 10:13 UTC, lpugin requested changes

2023-09-26 10:13 UTC, lpugin commented on src/importexport/mei/internal/meiexporter.cpp
> +    if (measure != mmR1 && mmR1->mmRestFirst()) {
you are still not checking the validity of `mmR1`

2023-09-26 10:13 UTC, lpugin commented on src/importexport/mei/internal/meiexporter.cpp
> +
Methods are kept ordered alphabetically.

2023-09-26 13:58 UTC, lpugin commented
@rettinghaus I think it would be simpler for such PRs to be made to https://github.com/rism-digital/MuseScore and we can the make a PR here once it is ready. @cbjeukendrup what do you think?

2023-09-26 14:41 UTC, cbjeukendrup commented
@lpugin I've no objections against that. Feel free to do whatever is most convenient for you :)

2023-09-26 15:10 UTC, lpugin commented
Yes, for cases like this one it would make it easier for me to review and create less noise on the main repo with things that are WIP steps in the MEI support.

2023-09-26 15:35 UTC, rettinghaus commented
Ok

2023-09-26 15:35 UTC, closed without merging