Introduce separate line width style for tab bends
musescore/MuseScore pull request #20242
Opened 2023-11-29 13:07 UTC by mike-spa

...and change the Bend style menu accordingly.

2023-11-29 13:41 UTC, oktophonie approved these changes

2023-11-29 13:48 UTC, oktophonie commented on src/notation/view/widgets/editstyle.ui
> +                 <string>Lien thickness: </string>
Line (typo)

2023-11-30 02:21 UTC, cbjeukendrup approved these changes

2023-11-30 14:01 UTC, bkunda requested changes
Pls just adjust the spin box for Standard Stave Line Thickness to adjust in 0.1 increments, rather than 1.0 [See video](https://www.dropbox.com/s/4j3obdt2ighcn15/line-thickness-settings.mov?dl=0)

2023-11-30 16:06 UTC, mike-spa commented
I think 0.1 is still way too coarse (a single +- 0.1 click already brings the values into unreasonable territory). So I actually made it 0.01, which feels better (and the reasonable territory is just few clicks away in either direction)

2023-12-05 10:49 UTC, bkunda approved these changes
Tested on macOS. FIXED:

2023-12-05 10:58 UTC, merged