'Show stem slash' property for all grace notes
musescore/MuseScore pull request #20890
Opened 2024-01-08 23:12 UTC by XiaoMigros

Resolves: #NNNNN 

This PR introduces a property 'Show stem slash' for all grace notes. The slash is shown by default for acciaccaturas, and is toggleable for all grace notes on a per-beam basis.

![image](https://github.com/musescore/MuseScore/assets/116587995/ba0bbdea-454d-4d65-9a9f-d6859ad6859f)

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

2024-01-09 13:17 UTC, oktophonie approved these changes

2024-01-17 11:04 UTC, bkunda requested changes
What a great little feature!

Two problems that need resolving before merging: 
- Stem slashes are not populating to parts
- The new "show stem slash" checkbox should be disabled when "stemless" is selected

Thanks!

2024-01-22 05:05 UTC, XiaoMigros commented
Point 2 has been addressed! For point 1, it seems that the property doesn't set for parts or linked staves, until the value is edited manually (works fine after that). I haven't yet been able to work out why...

2024-01-22 11:01 UTC, XiaoMigros commented
Ah, so that's what that method is for...

2024-01-25 23:09 UTC, XiaoMigros commented
The changes are all accounted for @bkunda

2024-02-02 11:28 UTC, cbjeukendrup commented
@XiaoMigros A rebase is needed due to recent changes in the MusicXML module

2024-02-02 12:47 UTC, mike-spa approved these changes

2024-02-05 09:53 UTC, bkunda approved these changes

2024-02-05 10:28 UTC, merged