symbols properties
musescore/MuseScore pull request #21110
Opened 2024-01-20 20:37 UTC by XiaoMigros

Resolves: #17116
Resolves: #18462

This PR introduces the options to scale and rotate symbol elements. These options can be managed via the properties tab, where it's now possible to change the symbol's font as well.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

2024-01-31 12:01 UTC, oktophonie approved these changes

2024-01-31 14:09 UTC, mike-spa approved these changes

2024-01-31 14:09 UTC, mike-spa commented on src/engraving/dom/symbol.cpp
> +            return PropertyValue::fromValue(nullptr);
Maybe using an empty string rather than a nullptr looks better (and same below)?

2024-02-07 09:42 UTC, bkunda commented
@XiaoMigros I'd love to be able to review this, but the macOS build appears to have failed.

2024-02-07 09:44 UTC, XiaoMigros commented
Very sorry about that, @cbjeukendrup has told me that I'm not the only encountering this issue so I hope it can be resolved soon..

2024-02-07 09:48 UTC, Jojo-Schmitz commented
That failure looks similar to that from #21360

2024-02-07 09:50 UTC, Jojo-Schmitz commented
As other more recent PRs succeed, maybe a rebase helps?

2024-02-07 10:24 UTC, XiaoMigros commented
Seems to have worked!

2024-02-07 13:55 UTC, bkunda requested changes
Nice work @XiaoMigros :-) 

1. I wonder whether we really need the font dropdown? @oktophonie do any of the other music fonts currently support the symbols in the master palette?
2. We need an icon for the button in properties (visible when multiple elements are selected). 

<img width="301" alt="Screenshot 2024-02-07 at 2 53 20 pm" src="https://github.com/musescore/MuseScore/assets/86290556/a2576352-7e95-4e65-a5c1-b2c3087da5ce">

I'd suggest @jessjwilliamson or @avvvvve whip up something for this and update the musescoreicon font (I don't mind who does it – you both can decide among yourselves :-))

2024-02-07 14:02 UTC, oktophonie commented
You can choose what music font to use in the master palette (by default, as of this PR, it'll be whatever music symbols font is currently in force). The font dropdown in Properties is the only means of changing this (which you may want or need to do it you ever change the music font, or for other supremely niche reasons).

The master palette shows SMuFL symbols, so they can exist in any SMuFL font.

2024-02-15 09:29 UTC, bkunda approved these changes

2024-02-15 13:25 UTC, cbjeukendrup approved these changes
A few minor comments, but generally looks good!

2024-02-15 13:25 UTC, cbjeukendrup commented on src/palette/view/widgets/symboldialog.cpp
> +        if (styleFont != "" && f->name() == styleFont) {
```suggestion
        if (!styleFont.empty() && f->name() == styleFont) {
```

2024-02-15 23:55 UTC, merged