Discard relative-y for lyric placement
musescore/MuseScore pull request #22740
Opened 2024-05-09 15:03 UTC by miiizen

Resolves: #22739 

This was introduced in https://github.com/musescore/MuseScore/pull/21862.  `relative-y` is usually garbage and unneeded anyway as we can lay out lyrics correctly ourselves.

2024-05-09 16:17 UTC, oktophonie approved these changes

2024-05-10 07:25 UTC, rettinghaus commented
@miiizen I agree that `default-y` and `relative-y` are usually garbage, but we could infer from that if lyrics are above or below the staff, so completely ignoring them maybe is not the ideal solution.

2024-05-10 10:57 UTC, rettinghaus requested changes
Great! Thanks.

2024-05-10 10:57 UTC, rettinghaus commented on src/importexport/musicxml/internal/musicxml/importmxmlpass2.h
> +    bool hasTotalY() const { return !muse::RealIsNull(m_defaultY) || !muse::RealIsNull(m_relativeY); }
```suggestion
    bool hasTotalY() const { return !muse::RealIsNull(m_defaultY) || !muse::RealIsNull(totalY()); }
```

2024-05-10 10:57 UTC, rettinghaus commented on src/importexport/musicxml/internal/musicxml/importmxmlpass2.cpp
> +        return totalY() < 0 ? u"above" : u"below";
Shouldn't this be the other way around?

2024-05-10 14:46 UTC, mike-spa approved these changes

2024-05-10 14:46 UTC, merged