Fix #22344: calculate divisions and duration using Fractions
musescore/MuseScore pull request #22977
Opened 2024-05-26 06:19 UTC by lvinken

Resolves: #22344

For historical reasons, the MusicXML exporter calculates the MusicXML divisions and duration values using ticks (the code predates the introduction of Fraction and was never updated). This works reasonably OK only for non-nested tuples up to quintuplets, but may introduce slight rounding errors.

Solution is to use Fractions in these calculations.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

2024-05-26 07:33 UTC, rettinghaus requested changes
Looks cool, thanks! One small copy / paste error.

2024-05-26 07:33 UTC, rettinghaus commented on src/importexport/musicxml/internal/musicxml/exportxml.cpp
> +//   fractionToStdString
```suggestion
//   durElemTicksToStdString
```

2024-05-26 18:45 UTC, lvinken commented on src/importexport/musicxml/internal/musicxml/exportxml.cpp
> +//   fractionToStdString
Thanks for catching this, done.

2024-06-07 07:04 UTC, RomanPudashkin approved these changes

2024-06-10 12:04 UTC, zacjansheski commented
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/22344 FIXED

2024-06-10 12:04 UTC, merged

2024-06-10 12:05 UTC, Jojo-Schmitz commented
Should this also make it into 4.3.2?

2024-06-10 12:16 UTC, RomanPudashkin commented
> Should this also make it into 4.3.2?

no, it's not a regression (at least not a new one)