Ensure hairpins and dynamic editable after inserted
musescore/MuseScore pull request #23284
Opened 2024-06-18 14:57 UTC by mike-spa

Resolves: #23140 

This ensures that hairpins and dynamics always remain in a selected and editable state after being dropped from palette, or otherwise inserted, or copy-pasted. It makes it possible, for example, to create a chain of dynamic-hairpin-dynamic very without moving the mouse out of the palette (one can just click dynamic-hairpin-dynamic).

2024-06-18 15:37 UTC, oktophonie approved these changes

2024-06-18 16:38 UTC, avvvvve requested changes
@mike-spa Found two more scenarios that need fixing:

Range selection + hairpin
1. Make a range selection (i.e. select a measure)
2. Insert a hairpin from palettes
3. The range stays selected, so shift + arrow just adjusts the range selection. Instead, the range selection should become deselected and the hairpin should be in the state where the handles are visible (which happens now when you repeat these steps with a dynamic instead of a hairpin).

Undo
1. Move a dynamic with shift + arrow
2. Undo
3. Hold shift, no grid overlay appears. Shift + arrows don't do anything. Have to reselect the dynamic to move it.

2024-06-19 09:40 UTC, mike-spa commented
@avvvvve 

> Range selection + hairpin

✅  Done!

> Undo

Very hard to do at the moment. The undo command preventively takes you out of any edit-mode you may be in (which it has to, cause the thing you're editing may not even exist after undo) and I can't find any simple (and safe) way of re-entering edit mode after. We'll have to postpone this bit

2024-06-19 12:30 UTC, avvvvve commented
@mike-spa Range selection looks good. Thanks for the context on the undo issues. I logged a feature request #23304 to address that someday.

Approving this now!

2024-06-19 12:39 UTC, RomanPudashkin approved these changes

2024-06-19 12:39 UTC, merged