Ignore timeTick segments for keyboard navigation movements
musescore/MuseScore pull request #23578
Opened 2024-07-11 10:26 UTC by mike-spa

Resolves: #23348

2024-07-11 10:33 UTC, Eism approved these changes

2024-07-11 13:38 UTC, shoogle requested changes
This works to avoid selecting the "time tick anchor" elements, but it's no longer possible to select hairpins and dynamics with Alt+Left and Alt+Right.

To be clear, I can select hairpins and dynamics when they start on a note or rest, but not when they have been dragged to start somewhere between a note/rest.

2024-07-11 14:09 UTC, mike-spa commented
> This works to avoid selecting the "time tick anchor" elements, but it's no longer possible to select hairpins and dynamics with Alt+Left and Alt+Right.
> 
> To be clear, I can select hairpins and dynamics when they start on a note or rest, but not when they have been dragged to start somewhere between a note/rest.

@shoogle but isn't it best then to let the keyboard navigation also walk through the timeTick segments like it does now? It may be a bit of an annoyance having to skip many of them, but it has the advantage of conveying to keyboard users the same information that we convey with the visuals. Otherwise I'd need some specs and examples on how you intend this to work: if we skip the anchors we will inevitably miss the starting/ending points of the hairpin, won't we?

2024-07-12 04:49 UTC, shoogle commented
@mike-spa, users can't interact with time tick elements, and it's not useful to be told that beat 1.5 occurs between beat 1 and beat 2, so there's really no reason to select these elements.

When the hairpin gets selected, the screen reader says "Hairpin, starts beat 1.5, ends beat 4", so blind users get all the information they need just from selecting the hairpin.

> If we skip the anchors we will inevitably miss the starting/ending points of the hairpin, won't we?

No, the `nextElement` function shouldn't return a time tick element, but it's fine to traverse those elements while looking for a non-time tick element to return.

Anyway, I've found the code I need to change to get this working, so I'll take this on once PR #23592 is merged.

2024-07-12 09:10 UTC, closed without merging