Allow for custom invisible color
musescore/MuseScore pull request #24256
Opened 2024-08-28 10:34 UTC by XiaoMigros

Resolves: #24054

Note this PR **doesn't** allow for a custom color of _selected_ invisible items, those are currently the selection color at 40% opacity

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [ ] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

2024-08-29 00:23 UTC, wizofaus commented
Tested this out, seems fine - I did originally think it'd be nice to have control over the degree of opacity for selected invisible notes but at least for me on my monitor I didn't feel any need to adjust it even after setting invisibleColor to #d0d0d0 (which is quite pale, but what I want - just enough to see there's something there but not getting in the way of what will be printed).

2024-08-29 00:23 UTC, wizofaus approved these changes
LGTM

2024-08-29 00:26 UTC, XiaoMigros commented
> I did originally think it'd be nice to have control over the degree of opacity for selected invisible notes

I believe that to be a separate issue - see #13652 
Thanks for taking a look!

2024-11-12 21:36 UTC, Jojo-Schmitz commented
Any reason not to merge this?

2024-11-12 23:51 UTC, cbjeukendrup approved these changes

2024-11-13 17:15 UTC, XiaoMigros commented
Rebased to include #24306, should be good now!

2024-11-15 23:57 UTC, avvvvve approved these changes
Looks good! "Invisible color" is kind of a funny title, but there's not really a better way to put it without making it longer.

2024-11-20 15:34 UTC, avvvvve requested changes
@XiaoMigros Zac just noticed that the invisible color is incorrectly being applied to the speaker icon in the sound flag button. That icon should just be black (#000000).

![image](https://github.com/user-attachments/assets/e377c17c-7b47-43a4-aad2-e07af9b745cb)

2024-12-01 21:11 UTC, XiaoMigros commented
Has been taken care of, thanks!

2024-12-02 18:46 UTC, avvvvve commented
@XiaoMigros That part looks good. I should've noted this originally, but the selected color of the sound flag is also incorrect. It should be the color of whichever voice it's applied to at full opacity. Thank you!

This PR:
<img width="228" alt="image" src="https://github.com/user-attachments/assets/6adf9aad-902b-4d26-9102-8aa84f605a2e">
<img width="270" alt="image" src="https://github.com/user-attachments/assets/e74f2302-f29a-4ad2-8038-cd88b877aa51">

Expected:
<img width="228" alt="image" src="https://github.com/user-attachments/assets/4986a21d-36bd-41df-b72d-12583f71d02b">
<img width="228" alt="image" src="https://github.com/user-attachments/assets/667da426-40ab-46b3-941f-0687f41c8fa1">

2024-12-02 18:46 UTC, avvvvve requested changes
(See above)

2024-12-02 22:07 UTC, XiaoMigros commented
I will admit, I haven't used sound flags often enough yet to know how they should've looked! Should be good now :)

2025-01-03 16:54 UTC, avvvvve approved these changes
Looks good! Thanks @XiaoMigros

2025-01-03 22:47 UTC, merged