Improvements to add text shortcuts - Part 3
musescore/MuseScore pull request #25255
Opened 2024-10-21 07:12 UTC by doss-eeic2024-03

Continuation of #25254

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

2024-10-29 17:20 UTC, mathesoncalum requested changes
This all looks great @CMakeScore - please [squash your commits](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow#squash) then we can get this tested. Thanks!

2024-10-30 06:18 UTC, CMakeScore commented
Thanks! I've squashed the commits now.

2024-10-30 09:23 UTC, mathesoncalum approved these changes

2024-10-30 14:32 UTC, zacjansheski commented
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/24548 (partially) FIXED

2024-10-30 14:41 UTC, merged