Improvements to add text shortcuts - Part 2
musescore/MuseScore pull request #25254
Opened 2024-10-21 07:11 UTC by doss-eeic2024-03

Continuation of #25252

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [x] I created a unit test or vtest to verify the changes I made (if applicable)

2024-10-29 16:13 UTC, mathesoncalum requested changes
After looking into the usage, I think it would be best to carry out your changes inside the `contextItem` method. I think your logic could be useful in other areas, and putting it here ensures we won't need to duplicate any code in future.

This does mean your solution will need to change a little. As a hint, you'll probably end up using a `INotationSelectionRangePtr` which you can acquire like this:
```
const INotationSelectionPtr sel = interaction->selection();
const INotationSelectionRangePtr range = sel->range();
```
But maybe you can find an even better way!

2024-10-30 11:09 UTC, bakajikara commented
I'm not entirely sure if this is the best approach, but I've implemented it in `contextItem`. I couldn't find a way to accomplish this without modifying the NotationSelectionRange class.

2024-10-30 11:13 UTC, CMakeScore commented
I am not sure I am doing the right thing, but I implemented it in `contextItem`.
I couldn't find a way to accomplish this without modifying the NotationSelectionRange class.

2024-11-01 17:51 UTC, mathesoncalum approved these changes
Looks good @CMakeScore - thanks!

You could have accessed the segment through `startMeasure` without modifying `NotationSelectionRange`, but I actually think this solution is nicer.

2024-11-01 20:34 UTC, zacjansheski commented
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved
https://github.com/musescore/MuseScore/issues/15406 FIXED
https://github.com/musescore/MuseScore/issues/24548 FIXED (Completely along with https://github.com/musescore/MuseScore/pull/25255)

2024-11-01 20:41 UTC, merged