[techdebt] Addresses code issues identified in issue 17082
musescore/MuseScore pull request #25537
Opened 2024-11-16 15:35 UTC by rpatters1

Resolves: #17082 

- Modified `Rest::downLine` to call `Rest::upLine`. This makes explicit that they are supposed to be identical functions.
- Modified `Score::cmdNextPrevSystem` to check `destinationMeasure` for `nullptr` before dereferencing it.

Unfortunately, I have been unable to figure out a test path in the app to step through these changes in the debugger. I would welcome comments on how to accomplish this.
It seems odd to me that `Rest::downLine` should be identical to `Rest::upLine`. If they should not be identical, we should be able to pinpoint a bug in behavior somewhere. I am not familiar enough with the code or the app to do so.

- [X] I signed the [CLA](https://musescore.org/en/cla)
- [X] The title of the PR describes the problem it addresses
- [X] Each commit's message describes its purpose and effects, and references the issue it resolves
- [X] If changes are extensive, there is a sequence of easily reviewable commits
- [X] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [X] There are no unnecessary changes
- [X] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

2025-01-14 14:13 UTC, Jojo-Schmitz commented
@mathesoncalum ?

2025-01-14 15:32 UTC, mathesoncalum reviewed
Thanks for the reminder @Jojo-Schmitz - this slipped through the cracks!

...

If I’m not mistaken `upLine` and `downLine` refer to the lines of the top and bottom notes of a chord so, IMO, it's not very cohesive to have them defined as pure virtual functions in `ChordRest`. Looks to me as though these methods (alongside the `line` methods) should be moved down into the `Chord` subclass and deleted completely the `Rest` subclass.   

A quick look at the usage seems to confirm this theory. `setSmallInnerBeamPos` is the only place where we try to call `upLine`/`downLine` on a `ChordRest` (and even then we’re ruling out rests with the `isChord` check).  

...

While we're at it, I’d love to give those `cmdNextPrev…` methods a more substantial makeover if you’re up for it? I think they'd be massively improved if we:

1. Make use of early returns to flatten the nesting. We could _maybe_ use some private helpers too, but I'm conscious of the size of `score.cpp` already.
2. Extract some of the more complex conditionals into well-labelled `bools`.
3. Eliminate the use of `auto` (we generally reserve `auto` for when we're working with iterators or other more complex types).

Thank you @rpatters1!

2025-01-14 18:59 UTC, rpatters1 commented
Is there a timeline for this (meaning a deadline)?

2025-01-14 20:00 UTC, mathesoncalum commented
> Is there a timeline...

Not really - take your time!

2025-01-15 16:49 UTC, rpatters1 commented
Do you mean (specifically) `cmdNextPrevSystem` and `cmdNextPrevFrame`?

2025-01-15 18:00 UTC, mathesoncalum commented
Yep - those two look most in need of a refactor to me.

2025-01-15 19:23 UTC, mathesoncalum commented
`cmdNextPrevSystem` is associated with the `next-system` and `prev-system` `UIActions`. In Preferences -> Shortcuts they're labelled as "Go to next system" and "Go to previous system". If you assign shortcuts there and add some breakpoints that should work. Similar story for `cmdNextPrevFrame`.

Interestingly `cmdNextPrevSection` isn't hooked up to anything anymore - looks to be a [known issue](https://github.com/musescore/MuseScore/issues/23012) (so probably leave that as-is for now, just thought I'd mention).

2025-01-16 13:21 UTC, rpatters1 commented
I made a couple stabs at refactoring `cmdPrevNextSystem` and I'm not convinced it is worth the risk. (At least, for me to attempt it.) Every approach I have tried doesn't really simplify the code that much. And given this code isn't even hooked up by default, I am wondering what the benefit is. Perhaps it requires someone with more domain knowledge than me to tackle it.

The safest approach would be to develop a unit test that runs through the scenarios with the current code and verifies they still work with the new code. This is starting to seem like its own separate project. At any rate, I think I've taken it as far as I am comfortable taking it, which is adding a couple more null checks.

I made the requested changes to Rest, Chord, and ChordRest.

2025-01-16 16:45 UTC, Jojo-Schmitz commented on src/engraving/dom/score.cpp
> +
This would only work (well, abort) in Debug builds.
If you'd use 
```cpp
    IF_ASSERT(cr) {
        return;
    }
```
It'd sill abort there in Debug builds, but return in non-Debug buils (with logging the issue)

2025-01-16 18:18 UTC, mathesoncalum requested changes
No problem @rpatters1. I totally understand if you’re not comfortable making drastic changes here - this is definitely quite a gnarly method to unpack.

I've left a couple points of feedback for you - thanks!

2025-01-16 18:18 UTC, mathesoncalum commented on src/engraving/dom/score.cpp
>              }
Hard to say what the original piece of code was trying to achieve here. I guess something like:
1. Try to set `destinationMeasure` using `prevMeasure`
2. If the above fails, try to set it with `prevMeasureMM` instead
3. If the above fails, return `cr`

I think there's a false assumption here which is that `prevMeasureMM` has the ability to return something non-null where `prevMeasure` can't. If you look at the implementations, for `prevMeasureMM` to succeed, there must be at least one non-null measure in the chain - and if there's one non-null measure in the chain, `prevMeasure` will have already returned it.

So i guess we can just reduce the check to:

```suggestion
        if (!(destinationMeasure = destinationMeasure->prevMeasureMM())) {
            return cr;
        }
```

Does that seem about right to you?

2025-01-17 04:22 UTC, rpatters1 commented on src/engraving/dom/score.cpp
>              }
I accepted this change then had second thoughts. My reading of the code is that it wants to give priority to `prevMeasure` over `prevMeasureMM`. So if what you say is true, then the code should be calling`prevMeasure` and skipping th call to `prevMeasureMM`, should it not?

2025-01-17 10:01 UTC, mathesoncalum commented on src/engraving/dom/score.cpp
>              }
The general (simplified) flow of this method goes something like this: 

1. Set `destinationMeasure` to the first measure of the current system 
2. Set `destinationMeasure` to the previous measure (this is the bit we’re working on)
3. Set `currentSystem` to `destinationMeasure`’s system 
4. Return the first `ChordRest` in `currentSystem`  

Whether you use `prevMeasure` or `prevMeasureMM` for step 2 doesn’t really matter from a functionality standpoint - we’re only interested in `destinationMeasure`’s system which will be the same in both cases. `prevMeasure` is indeed a slightly simpler method so there is perhaps an argument that we should use it instead (I’ll leave it up to you).

2025-01-17 10:05 UTC, mathesoncalum requested changes
Thanks for those tweaks @rpatters1! Please [squash this PR](https://musescore.org/en/handbook/developers-handbook/finding-your-way-around/git-workflow#squash) into one or two commits then we'll get give it a test.

2025-01-17 12:34 UTC, rpatters1 commented
Okay, I squashed it. Please do confirm that `prevMeasureMM` is the correct call rather than `prevMeasure`. In the previous code, `prevMeasure` was always called and `prevMeasureMM` never (based on your comments). Now it is the reverse.

```
            if (!(destinationMeasure = destinationMeasure->prevMeasureMM())) {
                return cr;
            }
```

2025-01-17 12:36 UTC, rpatters1 commented on src/engraving/dom/timesig.h
> +    void styleChanged() override;
Great! I hope that will be merged very soon, then. It creates so much build noise that it makes finding ones own errors tedious and difficult.

2025-01-17 12:39 UTC, Jojo-Schmitz commented on src/engraving/dom/timesig.h
> +    void styleChanged() override;
Fixing them here too shouldn't harm, as long it is done the very same way it won't create merge conflicts

2025-01-17 12:43 UTC, Jojo-Schmitz commented on src/engraving/dom/timesig.h
> +    void styleChanged() override;
Apropos build noise... my #25723 is awaiting review and merge since some 6 weeks now

2025-01-17 12:47 UTC, mathesoncalum commented
> Please do confirm that...

I addressed this [here](https://github.com/musescore/MuseScore/pull/25537#discussion_r1919857822). In summary, `prevMeasure` might be a smidge more efficient (and potentially safer since, like you say, it's the method we've always used here), but from a functionality perspective they should be exactly the same.

2025-01-17 12:58 UTC, mathesoncalum commented on src/engraving/dom/timesig.h
> +    void styleChanged() override;
> Fixing them here too shouldn't harm...

No, but for the sake of cohesion let's keep the changes relating to time signatures in the time signatures PR.

2025-01-17 13:00 UTC, Jojo-Schmitz commented on src/engraving/dom/timesig.h
> +    void styleChanged() override;
Or as a separate commit, just like in #26100. 
I've added it to my #25723 too now, along with one more macOS warning

2025-01-20 12:09 UTC, mathesoncalum approved these changes

2025-01-21 16:35 UTC, zacjansheski commented
Tested on MacOS 14, Windows 11, Ubuntu 22.04.3. Approved

2025-01-21 16:52 UTC, merged