fix issue 25617: prevent crash importing MusicXML file containing grace rest followed by tuple starting with rest
musescore/MuseScore pull request #25629
Opened 2024-11-24 20:01 UTC by lvinken

Resolves: #25617

See https://musescore.org/en/node/371987, which describes a crash caused by a MusicXML file containing a grace rest (which is not supported by libmscore and not handled correctly by the MusicXML importer). Trivial fix: ignore grace rests.

- [x] I signed the [CLA](https://musescore.org/en/cla)
- [x] The title of the PR describes the problem it addresses
- [x] Each commit's message describes its purpose and effects, and references the issue it resolves
- [x] If changes are extensive, there is a sequence of easily reviewable commits
- [x] The code in the PR follows [the coding rules](https://github.com/musescore/MuseScore/wiki/CodeGuidelines)
- [x] There are no unnecessary changes
- [x] The code compiles and runs on my machine, preferably after each commit individually
- [ ] I created a unit test or vtest to verify the changes I made (if applicable)

2024-11-25 16:24 UTC, miiizen commented
This looks ok, but I'd like to avoid the corruption which arises when the grace rest is part of a tuplet.  
My first thought is to include a dummy note which we make invisible if we're in a tuplet (`!(tupletAction & MusicXmlTupletFlag::NONE)`).  The pitch could just be set to the middle stave line.  This obviously isn't an ideal solution either, but will prevent corruption at least.

2024-11-25 17:17 UTC, Jojo-Schmitz commented
Another option might be a plain refusal to load that junk and tell the user to use the Dolte Plugin on Sibelius to create proper MusicXML...

2024-11-26 06:38 UTC, lvinken commented
@miiizen, what kind of corruption do you expect ? The change affects only grace rests, which have zero duration.

2024-12-06 10:36 UTC, rettinghaus requested changes

2024-12-06 10:36 UTC, rettinghaus commented on src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
> +        if (!grace) {
As this is indeed nonsense it would be preferred to have an early return after reading the attributes.

2025-01-14 14:10 UTC, Jojo-Schmitz commented on src/importexport/musicxml/internal/musicxml/import/importmusicxmlpass2.cpp
> +        if (!grace) {
This here is better in sync with other uses of `if (!grace) {` later

2025-02-27 08:46 UTC, merged