Fix MSVC compiler warnings
musescore/MuseScore pull request #25723
Opened 2024-12-04 09:21 UTC by Jojo-Schmitz

* reg.: declaration of 'noteEvent' hides previous local declaration (C4456)
* reg.: 'charToInt': not all control paths return a value (C4715)

2025-01-07 12:38 UTC, Jojo-Schmitz commented
Any special reason this is awaiting review/merge since more than a month now?

2025-01-17 13:06 UTC, Jojo-Schmitz commented on src/engraving/infrastructure/eidregister.cpp
> +#endif
Or are these calls needed for their side effects?

2025-01-17 13:39 UTC, mathesoncalum requested changes
Thanks for this @Jojo-Schmitz (and sorry for the delay). I've left some feedback points.

2025-01-17 13:39 UTC, mathesoncalum commented on src/musesounds/internal/musesoundsrepository.cpp
> +        for (size_t j = 0; j < soundsItems.size(); ++j) {
Can we use some more descriptive names here instead of `i` and `j`? 

e.g. `catalogIdx` and `soundIdx`

2025-01-17 13:39 UTC, mathesoncalum commented on src/importexport/guitarpro/internal/guitarbendimport/benddataprocessor.cpp
>              int pitch = bendNoteData.quarterTones / 2;
Regarding `pitch` - is there a reason not to leave it as-is and simply delete the second definition? Saves us doing the same calculation twice.

May as well make it `const` while you're at it.

2025-01-17 13:39 UTC, mathesoncalum commented on src/engraving/tests/playback/playbackeventsrendering_tests.cpp
> +    EXPECT_EQ(noteEvent0.arrangementCtx().nominalDuration, QUARTER_NOTE_DURATION + glissandoNoteDuration); // A4 + 1st glissando note
Let's use a more descriptive name - perhaps `resultingNoteEvent` (same for the other `noteEvent0`).

2025-01-17 13:40 UTC, mathesoncalum commented on src/engraving/infrastructure/eidregister.cpp
> +#endif
It would appear so (since we're using `emplace`). Let's leave this as-is for now.

2025-01-17 14:03 UTC, Jojo-Schmitz commented on src/engraving/infrastructure/eidregister.cpp
> +#endif
OK, I'll use
```cpp 
    UNUSED(inserted)
```
to silence the warning

2025-01-17 14:04 UTC, Jojo-Schmitz commented on src/musesounds/internal/musesoundsrepository.cpp
> +        for (size_t j = 0; j < soundsItems.size(); ++j) {
I sure could, but being as local as they are I found that to verbose

2025-01-17 14:07 UTC, Jojo-Schmitz commented on src/engraving/tests/playback/playbackeventsrendering_tests.cpp
> +    EXPECT_EQ(noteEvent0.arrangementCtx().nominalDuration, QUARTER_NOTE_DURATION + glissandoNoteDuration); // A4 + 1st glissando note
Yes, agreed. I'm just lacking the creativity to invent names

"There are 2 complicated things with computing: cache invalidation and naming... things"

2025-01-17 14:11 UTC, Jojo-Schmitz commented on src/importexport/guitarpro/internal/guitarbendimport/benddataprocessor.cpp
>              int pitch = bendNoteData.quarterTones / 2;
Deleting the second is of course possible, but as it is used only in that (and one other) scope, but not others, I deleted the first, to keep them as close to their score as possible. Still results in code duplication.
OK, will amend.

2025-01-17 14:25 UTC, mathesoncalum commented on src/musesounds/internal/musesoundsrepository.cpp
> +        for (size_t j = 0; j < soundsItems.size(); ++j) {
All good. I'm personally just not a big fan of the `i-j-k` thing and prefer a bit of verbosity given the option. Either way, I'll survive if you want to leave it as-is.

Ideally we'd just use a range-based for loops here, but that's not possible with our current `JsonArray` implementation (and probably not worth the hassle for the time being).

2025-01-17 16:23 UTC, mathesoncalum approved these changes

2025-01-17 16:23 UTC, merged