update to latest SMuFL version 1.3
musescore/MuseScore pull request #4883
Opened 2019-04-08 07:37 UTC by Jojo-Schmitz

2019-04-11 07:17 UTC, lasconic commented
Maybe sym.cpp and sym.h need to be updated too ?

2019-04-11 07:53 UTC, Jojo-Schmitz commented
Hmm, true, very good point, there are a few new glyphs. Only not even Bravura contains them yet as far as I can tell

2019-04-11 07:59 UTC, Jojo-Schmitz commented
Does it matter where exactly they get added to sym.{cpp,h}?

2019-04-11 08:07 UTC, Jojo-Schmitz commented
Ah, looks like they are in strict alphabethical order in sym.{cpp,h}
Problem: `ornamentMordentInverted` got removed, but is used outside sym.{cpp,h}

2019-04-11 08:24 UTC, Jojo-Schmitz commented
Actually `ornamentMordentInverted` turned into `ornamentMordent` that into `ornamentShortTrill`, codepoint-wise

2019-04-11 08:26 UTC, Jojo-Schmitz commented
Didn't you have some (Python?) script to update those files automagically?

2019-04-11 12:29 UTC, Jojo-Schmitz commented
Done, but I'm not sure whether I got the `ornamentMordentInverted` vs. `ornamentMordent` and `ornamentShortTrill` right in all cases

2019-04-11 12:33 UTC, Jojo-Schmitz commented
Something is bad, need to check again, seems somehow the order of the glyphs got messed up

2019-04-11 12:44 UTC, lasconic commented
I used this script in the past : https://gist.github.com/lasconic/be08234b3dd074e99edc1fb060f0abcb

2019-04-11 13:35 UTC, Jojo-Schmitz commented
Workspace needs some work still, the Ornaments palette needs updating

2019-04-11 13:42 UTC, Jojo-Schmitz commented
@lasconic could you run your script to verify my 'handmade' changes?

2019-04-11 15:17 UTC, Jojo-Schmitz commented
as far as I can tell the Travis CO mtests failures are all due to the mordent changes. These definitly need a good review before looking at how to fix those mtest failures

2019-05-02 15:02 UTC, mirabilos commented
Please also update the Unix manpage https://github.com/musescore/MuseScore/blob/master/build/Linux%2BBSD/mscore.1.in#L511 in the same commit, so the data stays consistent.

Thanks!

2019-05-02 16:15 UTC, Jojo-Schmitz commented
done

2019-05-02 18:09 UTC, RobFog commented
Might make sense to document somewhere that updating the manpage should go along with an SMuFL update.

2019-05-03 06:23 UTC, Jojo-Schmitz commented
There's no suitable place for that I'm affraid

2019-05-03 07:48 UTC, RobFog commented
The Developer Handbook would seem like a good place.

@mirabilos Are there other components where Unix manpage updates are also necessary?

2019-05-03 12:49 UTC, mirabilos commented
Robbie dixit:

>@mirabilos Are there other components where Unix manpage updates are
>@also necessary?

The hyperlinks in the SEE ALSO section (immediately above the
STANDARDS section in which the SMuFL version is noted), and in
the STANDARDS section, MusicXML, SoundFont and SFZ.

I did a quick pass through the manpage, and I think these are it.

Command line option changes (in mscore/musescore.cpp mostly)
and changes to the portable application mechanism need to be
also reflected.

2019-05-03 15:07 UTC, Jojo-Schmitz commented
I meant no good place in the code, so nothing for this PR

2019-05-03 18:10 UTC, RobFog commented
Thanks, @mirabilos.

> I meant no good place in the code, so nothing for this PR
Ah, yes.

@Jojo-Schmitz, do you think this should go into the Handbook?

2019-08-28 09:07 UTC, anatoly-os commented
@Jojo-Schmitz what is the reason to update the font? Some known issues with current version? User requests?

2019-08-28 09:42 UTC, Jojo-Schmitz commented
Just to stay up-to-date and on par with Steinberg/Dorico ;-)

2019-08-28 09:49 UTC, anatoly-os commented
So, there were no requests or known bugs, right?

2019-08-28 10:02 UTC, Jojo-Schmitz commented
None for MuseScore, but apparently some for SMuFL, otherwise there won't be changes there?

2019-08-29 13:20 UTC, MarcSabatella commented
In general, I certainly favor keeping up to date with the latest version of this (or any) font, as presumably there are improvements we would want to take advantage of.  But we'd also want to make sure there aren't incompatible changes that could bite us.  Didn't this happen recently-ish with, hmm, position of repeat dots or something like that?

2019-08-29 14:34 UTC, Jojo-Schmitz commented
That's why I'd like it in now, with a proper Beta phase

2019-09-07 14:53 UTC, Jojo-Schmitz commented
As per https://github.com/w3c/smufl/milestone/3 SMuFL 1.4 is due by the end of this year

2019-09-07 15:58 UTC, Jojo-Schmitz commented
As per https://github.com/w3c/smufl/milestone/3 SMuFL 1.4 is due by the end of this year. But apparently no work on it has yet started...

2020-03-12 09:09 UTC, dmitrio95 commented
@Jojo-Schmitz could you please force-push changes here to trigger vtest (see my comment in https://github.com/musescore/MuseScore/pull/4879#issuecomment-598080805)?

2020-03-12 09:18 UTC, Jojo-Schmitz commented
done

2020-03-12 12:14 UTC, AntonioBL commented
There is a change in musejazz-4, see https://github.com/musescore/MuseScore/suites/516146421/artifacts/2824761
Unfortunately, the bot for commenting the PR didn't work 😞 
Maybe adding a log warning could be the best option.

2020-03-12 12:59 UTC, Jojo-Schmitz commented
seen that but couldn't make any sense of it

2020-03-12 13:03 UTC, Jojo-Schmitz commented
So yes, something to fix in this PR I guess

2020-03-12 13:54 UTC, Jojo-Schmitz commented
Not sure what/how though :-(

2020-03-12 15:24 UTC, Jojo-Schmitz commented
OK, the difference is that the vtest scores for  Emmentaler, Bravura and Gonville are MuseScore 2 score, and so run thru `read206()`, while the museJazz one is a MuseScore 3 score. I could fix that musejazz-4.mscx by  turning `ornamentMordentInverted` into `ornamentMordent` and that into `ornamentShortTrill`, but that would rather be curing the symptoms, wouldn't it?

2020-03-12 16:17 UTC, Jojo-Schmitz commented
We'd have a down rev problem too, as older versions of MuseScore won't understand the new `ornamentShortTrill` and not render it at all.

2020-03-12 16:37 UTC, Jojo-Schmitz commented
Submitted an issue for SMuFL: https://github.com/w3c/smufl/issues/119

2020-03-18 12:41 UTC, dmitrio95 commented
Let's wait for a reply in https://github.com/w3c/smufl/issues/119 then prior to merging this PR.

2020-03-18 13:41 UTC, Jojo-Schmitz commented
Yes, I'm afraid we'd have to. I should have raised that issue there long ago.

2020-04-11 10:57 UTC, RobFog commented
Shouldn't there be some indication in form of a label or something to indicate this pull request is waiting on a reply to the issue mentioned above?

2020-04-11 11:02 UTC, Jojo-Schmitz commented
Maybe, but this is beyond my control. 
Also I doubt whether there will ever be a reply, a full month passed already :-(

2020-04-11 13:19 UTC, RobFog commented
Oh, nevermind, I see Dimitri did just that. Sorry for the noise!

2020-07-06 11:06 UTC, Jojo-Schmitz commented
For master this needs a rebase meanwhile, not sure whether it does for 3.x too though, and whether it has a chance to get merged into 3.x.

2020-09-06 08:47 UTC, Jojo-Schmitz commented
The issue with Mordent, Inverted Mordent and Short Trill just came up in the [German MuseScore forum](https://musescore.org/de/node/310109), and about a year ago already on Transifex by a Japanese translator, as a commet to the translation of Mordent and Inverted mordent.

2020-09-06 11:21 UTC, Jojo-Schmitz commented
> Maybe for scores where we do find an `ornamentMordentInverted` we'd need to fix that somehow (like making it an `ornamentMordent`), but what about the `ornamentMordent`? There's no way to tell whether it is the old one and should get changed to the new `ornamentShortTrill`, or whether it is the new one already and needs to stay as is.

Actually we now have such a method, it is being used in several other places now, like for the chord symbols playback

2020-09-06 12:47 UTC, Jojo-Schmitz commented on libmscore/articulation.cpp
> +        if (!programVersion.isEmpty() && programVersion < "3.5.1") {
This might need to get adjusted, depending on when and were this PR gets merged

2020-09-06 14:47 UTC, Jojo-Schmitz commented
I believe with that out of the way there's no reason to wait on that SMuFL issue anymore, that "question" label could get removed and this PR merged.

2020-09-07 12:40 UTC, Jojo-Schmitz commented on libmscore/articulation.cpp
> +        if (!programVersion.isEmpty() && programVersion < "3.6") {
This might need to get adjusted, depending on when and were this PR gets merged

2020-10-24 21:07 UTC, Jojo-Schmitz commented
I guess I'll include the latest SMuFL changes too, https://github.com/w3c/smufl/pull/135, https://github.com/w3c/smufl/pull/129 and https://github.com/w3c/smufl/pull/120 (where the last one doesn't affect us at all as far as I can tell)

2020-10-25 05:16 UTC, mirabilos commented
@Jojo-Schmitz we need to coordinate the sym.{cpp,h} update, I wrote the script I told you about, but it’ll probably need changes for master.

Do you wish for me to branch off this PR of yours, add a commit on top (like I did in #6742 for 3.x), and then you can pull from my branch and update this PR?

2020-10-25 08:10 UTC, Jojo-Schmitz commented
Yes, let's do that (now that I've a) included the latest SMuFL updates and b) fixed my most stupid mistakes)

2020-10-25 08:11 UTC, Jojo-Schmitz commented on libmscore/articulation.cpp
> +        if (!programVersion.isEmpty() && programVersion < "3.6") {
As the corresponding PR had been merged into 3,x, this here is correct and can stay as is.

2020-10-25 22:13 UTC, mirabilos commented
OK, if you merge https://github.com/Jojo-Schmitz/MuseScore/pull/72 into your `smufl` branch, this PR will (AIUI) get updated with my commit on top of yours, and you can easily review the changes there.

2020-10-25 22:24 UTC, Jojo-Schmitz commented
I hope I didn't screw that up?

2020-10-25 22:28 UTC, mirabilos commented
$ git diff origin/smufl-ms4..jojo/smufl | wc
          0       0       0

Nope, looks good to me ☺

2020-10-25 22:37 UTC, Jojo-Schmitz commented
It doesn't happen often to me to be on this side of the fence ;-)

2020-10-25 22:48 UTC, Jojo-Schmitz commented
OK, there's one thing left to do I think, see https://github.com/w3c/smufl/issues/119#issuecomment-716217053, we'd need to deal with the Problem: `ornamentMordentInverted` vs. `ornamentMordent` vs. `ornamentShortTrill`. But we'd need to do this for 3.x (where this change hare has been merged already) and for master, in either case when 'importing' pre-3.6 scores, so I guess, I'd better deal with this in separate PRs, meanwhile this here can get merged.

2020-10-26 08:12 UTC, Jojo-Schmitz commented
Oops, actually this is exactly what I did already, somehow I managed to confuse myself ;-)
So all is honky-dory and sorted, see https://github.com/musescore/MuseScore/pull/4883/files#diff-aa3aa491a9912868efe44de537be8f729e376388336aa5d0d7de08b126c66e24R142-R147

2020-10-28 23:14 UTC, mirabilos approved these changes

2020-10-28 23:15 UTC, mirabilos requested changes

2020-10-28 23:15 UTC, mirabilos commented on fonttools/smufl2sym.sh
> +	echo '    // SMuFL standard symbol namess }}}'
names**s** (two ‘s’)

2020-11-10 13:10 UTC, merged