fix #310869: crash on DPI change in preferences
musescore/MuseScore pull request #6579
Opened 2020-09-25 15:51 UTC by MarcSabatella

Resolves: https://musescore.org/en/node/310869

The crash is a null pointer dereference.
We are processing a spin box but referencing a combo box.
This appear to me to have been a copy/paste error.
Comparing against similar code to handle "int" spin boxes,
it seems this line shouldn't be needed at all,
so I have removed it.

2020-09-25 17:55 UTC, Jojo-Schmitz commented on mscore/preferenceslistwidget.cpp
> +                  //_initialEditorIndex = _editorComboBox->currentIndex();
Why not just removing the line?

2020-09-25 18:28 UTC, SKefalidis commented on mscore/preferenceslistwidget.cpp
> +                  //_initialEditorIndex = _editorComboBox->currentIndex();
Remove it, it's a copy-paste mistake.

2020-09-25 18:29 UTC, SKefalidis commented
The fix is correct :+1: :^)

2020-09-25 18:33 UTC, SKefalidis commented
Actually, you should move it over to the combo box part of apply.

2020-09-25 18:35 UTC, SKefalidis requested changes
Move it here.
```
else if (_editorComboBox) {
            double newValue = _editorComboBox->currentData().toDouble();
            _initialValue = newValue;
            PreferenceItem::apply(newValue);
        }
```

Otherwise `isModified` will not work properly.

2020-09-25 20:56 UTC, MarcSabatella commented
OK, done.  Probably not testable even by hand, unless there really is a double combobox somewhere?

2020-09-25 21:07 UTC, SKefalidis commented
> OK, done. Probably not testable even by hand, unless there really is a double combobox somewhere?

You are right @MarcSabatella. I don't think that there is a double combobox somewhere, I added it just in case we need it in the future.

2020-09-26 11:01 UTC, Jojo-Schmitz approved these changes

2020-10-02 18:24 UTC, merged