add transpose function to pluginAPI::score
musescore/MuseScore pull request #7082
Opened 2020-12-13 03:23 UTC by Marr11317

Resolves: No issue in tracker

Adds ability to transpose a score from plugin.

NOTE: I still cannot build Musescore on my PC, so I will test the generated artifacts when the CI outputs them.

- [ ] I signed [CLA](https://musescore.org/en/cla)
- [ ] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [ ] I made sure the code compiles on my machine
- [ ] I made sure there are no unnecessary changes in the code
- [ ] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [ ] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [ ] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

2020-12-13 07:33 UTC, Jojo-Schmitz requested changes

2020-12-13 08:21 UTC, dmitrio95 commented
The build fails because the enumerations used in `DECLARE_API_ENUM` declarations (`Ms::TransposeMode`, `Ms::TransposeDirection` and `Ms::Key`) are not registered to the Qt meta-object system and thus there is no `QMetaEnum` for them which can be used to obtain names of the corresponding enumerators. This can be fixed using one of the following approaches:
1. Move the enumeration to `types.h` file and add `Q_ENUM_NS` declaration for this enumeration (see, for example, 54c64e1603e32c4cb16cfd59a5d46e108a7aac47). Moving to `types.h` is needed since `Q_ENUM_NAMESPACE` needs to be in the file which contains `Q_NAMESPACE` declaration which cannot be added to more than one file in the same namespace, see [QTBUG-68611](https://bugreports.qt.io/browse/QTBUG-68611).
2. Put the enumeration to some class and register it to the meta-type system with `Q_ENUM` macro. This is something which I have implemented with `BEGIN_QT_REGISTERED_ENUM` and `END_QT_REGISTERED_ENUM` macros in #6065 and #6205. Due to Qt moc limitations, those macros need to be duplicated across files which doesn't make it a good solution either. I used it in those cases since the relevant enumerations contain large number of elements and are relatively often changed in the process of MuseScore development (so moving the enumerations would make it more difficult to track changes history and do a rebase when necessary), but it may not worth it for smaller enumerations like those touched in this PR.

Of course, there may possibly be other solutions, I just listed those which are currently being used for that purpose.

2020-12-14 07:39 UTC, Jojo-Schmitz commented
Seems the `Ms::Key` is lacking that
```
      ///.\{
      ...
      ///.\}
```
'decorations', might that be the cause for the build failure?

2020-12-14 08:14 UTC, dmitrio95 commented
Yes, `Key` also needs the same treatment as the other two enums.

The `///.\{`-`///.\}` thing is needed to make Doxygen display all enumeration's members in the generated documentation without having to document them all manually. Doxygen somehow doesn't display enum members which don't have documentation, but writing documentation for all of them often doesn't make sense (especially if such documentation would be trivial as enumerators names are already self-describing). So this thing exploits [`DISTRIBUTE_GROUP_DOC`](https://www.doxygen.nl/manual/config.html#cfg_distribute_group_doc) Doxygen option to add an empty documentation to all members of the enumeration so they all get listed in tables like [this one](https://musescore.github.io/MuseScore_PluginAPI_Docs/plugins/html/namespace_ms.html#a16b11be27a8e9362dd122c4d879e01ae). So this is needed just to get enumerators displayed in the documentation correctly, and this can be achieved without that by adding documentation comments to all of the enumerators.

2021-03-15 15:54 UTC, closed without merging

2021-03-15 16:09 UTC, Jojo-Schmitz commented
why?

2021-03-15 17:56 UTC, Marr11317 commented
I'll wait for the plugin api to be ported to the 4.x codebase before reworking on it.