Allow the user to customize background when exporting as PDF/PNG/SVG
musescore/MuseScore pull request #7500
Opened 2021-02-12 13:24 UTC by sidharth-anand

Resolves: https://musescore.org/en/node/293370

This patch provides the user complete control over the background when exporting the score to a PDF/PNG/SVG file, allowing the user to choose between a transparent background, the background currently used in the score (both solid colors and images) or a custom color.

![image](https://user-images.githubusercontent.com/55060749/107772564-6560d700-6d62-11eb-9896-2660b4f6ecea.png)

Note: To be able to see  the transparent background when exporting as a pdf, you will have to turn on the "Show Transparency Grid" or equivalent option in your pdf viewer or the transparent area gets filled with white by default.

- [x] I signed [CLA](https://musescore.org/en/cla)
- [x] I made sure the code in the PR follows [the coding rules](https://github.com/musescore/Documentation/blob/master/CodeGuidelines.md)
- [x] I made sure the code compiles on my machine
- [x] I made sure there are no unnecessary changes in the code
- [x] I made sure the title of the PR reflects the core meaning of the issue you are solving
- [x] I made sure the commit message(s) contain a description and answer the question "Why do those changes fix that particular issue?" or "Why are those changes really necessary as improvements?"
- [x] I made sure the commit message title starts with "fix #424242:" if there is a related issue
- [ ] I created the test (mtest, vtest, script test) to verify the changes I made

2021-02-12 14:19 UTC, Jojo-Schmitz requested changes

2021-02-12 14:20 UTC, Jojo-Schmitz commented
I don't think the effect these changed have on the vtests are really wanted.

2021-03-01 15:43 UTC, cbjeukendrup commented on mscore/exportdialog.ui
> +   </property>
Why are the margins changed? I don't think this is intended... please undo this (remove these 12 lines).

2021-03-01 18:43 UTC, cbjeukendrup commented
I would like to suggest a quick design tweak: (see mock-up)
<img width="963" alt="Schermafbeelding 2021-03-01 om 19 40 42" src="https://user-images.githubusercontent.com/48658420/109542933-03c09c80-7ac6-11eb-84b1-3aa8fe1cf420.png">

2021-03-10 17:57 UTC, vpereverzev commented
Hi @sidharth-anand, we're not planning to release 3.x anymore, but I guess it might be useful for 4.0
Is it already included in your counter-part for master? If so, I'd close this one

2021-03-10 17:58 UTC, Jojo-Schmitz commented
Even if it is, please merge to 3,x too, it is easier to text it with a 3.x development build

2021-03-10 18:00 UTC, Jojo-Schmitz commented
And that preferences stuff is not yet in master anyhow as far as I can tell

2021-03-10 18:05 UTC, Jojo-Schmitz commented
Anyway: as far as I can see this PR here is not included in the other one

2021-03-11 05:33 UTC, sidharth-anand commented
@vpereverzev it's not included in my PR for the export dialog currently. I was thinking of making a separate PR porting this to master once the export dialog and the preferences and somewhat stable in master

2021-03-17 08:02 UTC, Jojo-Schmitz commented
Needs #7704 too

2021-09-04 10:26 UTC, Jojo-Schmitz commented
Wouldn't that new preference also need to get added to the dialog in Edit > Preferences > Export > PNG and ...PDF (there is none for ...SVG)?

2021-09-04 10:28 UTC, Jojo-Schmitz commented
Have you done a port of this to master meanwhile?

2022-12-20 08:55 UTC, RomanPudashkin commented
3.x is closed for any changes

2022-12-20 08:55 UTC, closed without merging